name: 
    CI

on: 
   push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up and test
        run: |
          make setup
          make test
          make lint